package com.lxisoft.scripts;
public class RomanceScript extends Script
{
	
}


Zainuddin : ende makale.... 
Shalini :  ende makale.... 
Zainuddin : Kaigal kurachloodi melotuyarthi....enit melle munnot chalikuga...ende makale....
Shalini : ende makale........................
Zainuddin : Pokkilkudiyude veraruth adyam avarenne tholpichu....
Shalini : Pokkilkudiyude veraruth adyam avarenne tholpichu........................
Zainuddin : Mulakannugalil chenninayagam puratti ningalude varanda chundugalk madhruthvathinde madhuram nishedich veendum avarenne tholpichu,,,
Shalini : veendum tholpichu.....
Zainuddin : aaaaiiiiiii....
Shalini : aaaiiii
Zainuddin : ivide alla...avide.......Veendum Tholvigaletuvangan ende jenmam...
Shalini : Anyayanaval......apalayanaval....
Zainuddin: Parithyakthayanaval.....
Shalini : Kaalathinde idanazhiyil  kaalidariveezhan Vidhikapetaval..............
Zainuddin: Evideyaanivalkoru thaang...evideyan Deivam.............
Chacko : Evideyan Purathekulla Vazhi.........................oh hoi....oh hoi......oh hoi............
